baseURL = "https://example.org/"
defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "Hisham's Blog"

[menu]
  [[menu.main]]
    # Display name
    name = "Home"
    # Relative URL slug (appended to baseURL)
    url = "/"
    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 1
      [[menu.main]]
    # Display name
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    # Display name
    name = "Posts"

    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
